name: "test-local"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      # - run: npm test
      - uses: ./
        with:
          msg: |
            Hello!
            ğŸŒ
            **bold**
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
